import "dotenv/config";

export const env = {
  DOMAIN: process.env.DOMAIN!,
  TEAM_ID: process.env.TEAM_ID!,
  ACCESS_HISTORY_SSID: process.env.ACCESS_HISTORY_SSID!,
  LECTURE_HISTORY_SSID: process.env.LECTURE_HISTORY_SSID!,
  STUDENT_LIST_SSID: process.env.STUDENT_LIST_SSID!,
  GENERAL_CHANNEL_ID: process.env.GENERAL_CHANNEL_ID!,
  GENERAL_CHANNEL_MAIL_ADDRESS: process.env.GENERAL_CHANNEL_MAIL_ADDRESS!,
  MAIL_APP_TOKEN: process.env.MAIL_APP_TOKEN!,
  MAIL_APP_ENDPOINT: process.env.MAIL_APP_ENDPOINT!,
  GRAPH_EXPLORER_ACCESS_TOKEN: process.env.GRAPH_EXPLORER_ACCESS_TOKEN!,
  TEAMS_AUTHTOKEN: process.env.TEAMS_AUTHTOKEN!,
  TEAMS_SKYPETOKEN_ASM: process.env.TEAMS_SKYPETOKEN_ASM!,
  TA_SSID: process.env.TA_SSID!,
  GOOGLE_SERVICE_CLIENT_EMAIL: process.env.GOOGLE_SERVICE_CLIENT_EMAIL!,
  GOOGLE_SERVICE_PRIVATE_KEY: process.env.GOOGLE_SERVICE_PRIVATE_KEY!,
};
