import "dotenv/config";

export const env = {
  DOMAIN: process.env.DOMAIN!,
  TEAM_ID: process.env.TEAM_ID!,
  GENERAL_CHANNEL_MAIL_ADDRESS: process.env.GENERAL_CHANNEL_MAIL_ADDRESS!,
  MAIL_APP_TOKEN: process.env.MAIL_APP_TOKEN!,
  MAIL_APP_ENDPOINT: process.env.MAIL_APP_ENDPOINT!,
  GRAPH_EXPLORER_ACCESS_TOKEN: process.env.GRAPH_EXPLORER_ACCESS_TOKEN!,
  TA_SSID: process.env.TA_SSID!,
  GOOGLE_SERVICE_CLIENT_EMAIL: process.env.GOOGLE_SERVICE_CLIENT_EMAIL!,
  GOOGLE_SERVICE_PRIVATE_KEY: process.env.GOOGLE_SERVICE_PRIVATE_KEY!,
};
